export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENT_FAILED';

export const PURCHASE_SUCCESS = 'PURCHASE_SUCCESS';
export const PURCHASE_FAIL = 'PURCHASE_FAIL';
export const PURCHASE_LOADING_SET = 'PURCHASE_LOADING_SET';
export const PURCHASE_INIT = 'PURCHASE_INIT';

export const GET_ALL_ORDERS = 'GET_ALL_ORDERS';
export const SET_ORDERS = 'SET_ORDERS';
export const GET_ORDERS_FAILED = 'GET_ORDERS_FAILED';
